"""Agent implementations for prompt orchestration."""

from .planner import Planner, Plan, PlanStep
from .judge import (
    Judge,
    JudgeError,
    Judgment,
    PairwiseJudgment,
    LegacyJudge,
    SingleEvalResult,
    PairwiseEvalResult,
)
from .optimizer import (
    PromptOptimizer,
    OptimizerError,
    OptimizationResult,
    PromptAnalysis,
)
from .hallucination_checker import (
    HallucinationChecker,
    HallucinationReport,
    ClaimVerification,
)
from .media_optimizer import (
    MediaOptimizer,
    MediaOptimizerError,
    MediaOptimizationResult,
    MediaAnalysis,
)
from .agent_optimizer import (
    AgentOptimizer,
    AgentAnalyzer,
    AgentScorer,
    AgentConfig,
    AgentOptimizationResult,
    ScoringResult,
    FrameworkDetection,
    detect_framework,
    parse_crewai_config,
    parse_autogen_config,
    parse_langgraph_config,
    score_role_specificity,
    score_goal_clarity,
    score_termination_criteria,
    score_boundaries,
    score_tool_guidance,
    score_handoff_clarity,
)

__all__ = [
    "Planner",
    "Plan",
    "PlanStep",
    "Judge",
    "JudgeError",
    "Judgment",
    "PairwiseJudgment",
    "LegacyJudge",
    "SingleEvalResult",
    "PairwiseEvalResult",
    "PromptOptimizer",
    "OptimizerError",
    "OptimizationResult",
    "PromptAnalysis",
    "HallucinationChecker",
    "HallucinationReport",
    "ClaimVerification",
    "MediaOptimizer",
    "MediaOptimizerError",
    "MediaOptimizationResult",
    "MediaAnalysis",
    # Agent optimization
    "AgentOptimizer",
    "AgentAnalyzer",
    "AgentScorer",
    "AgentConfig",
    "AgentOptimizationResult",
    "ScoringResult",
    "FrameworkDetection",
    "detect_framework",
    "parse_crewai_config",
    "parse_autogen_config",
    "parse_langgraph_config",
    "score_role_specificity",
    "score_goal_clarity",
    "score_termination_criteria",
    "score_boundaries",
    "score_tool_guidance",
    "score_handoff_clarity",
]
